/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "surface": "#f8f9fa",
        "on-secondary-container": "#581200",
        "on-primary-fixed": "#0b1649",
        "tertiary-container": "#441e00",
        "outline-variant": "#c6c5d0",
        "outline": "#767680",
        "on-primary-fixed-variant": "#3a4376",
        "surface-container-low": "#f3f4f5",
        "on-surface": "#191c1d",
        "tertiary-fixed-dim": "#fbb88b",
        "on-surface-variant": "#45464f",
        "primary-fixed-dim": "#bac3ff",
        "primary-container": "#1a2456",
        "surface-bright": "#f8f9fa",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "background": "#f8f9fa",
        "surface-container": "#edeeef",
        "on-secondary-fixed-variant": "#872000",
        "surface-dim": "#d9dadb",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "secondary": "#b12d00",
        "secondary-container": "#fe5e2f",
        "tertiary": "#250d00",
        "inverse-primary": "#bac3ff",
        "on-primary-container": "#838cc5",
        "surface-tint": "#515b90",
        "primary-fixed": "#dee1ff",
        "surface-variant": "#e1e3e4",
        "on-secondary-fixed": "#3b0900",
        "secondary-fixed": "#ffdbd1",
        "tertiary-fixed": "#ffdcc6",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f0f1f2",
        "on-tertiary-fixed": "#311400",
        "on-tertiary-fixed-variant": "#693b19",
        "on-background": "#191c1d",
        "secondary-fixed-dim": "#ffb5a0",
        "inverse-surface": "#2e3132",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#bd8259",
        "primary": "#030d41",
        "on-secondary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "8px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        gutter: "24px",
        "margin-edge": "32px",
        "stack-md": "16px",
        "container-max": "1440px",
      },
      fontFamily: {
        "data-mono": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Source Serif 4", "serif"],
        "headline-lg": ["Source Serif 4", "serif"],
        "label-bold": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Source Serif 4", "serif"],
        "headline-md": ["Source Serif 4", "serif"],
      },
      fontSize: {
        "data-mono": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "label-bold": ["12px", { lineHeight: "16px", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
